### ISSUE TITLE
Cached Dialogs are getting deleted from the Database after you kill the app.

### ISSUE THREAD

**Issue by Anurag15990** [QuickBlox/q-municate-services-ios#123]
Hey, 

I am facing this weird issue that the cached local dialogs in the db are getting deleted from the database after you kill the app. I would require your help to resolve this issue. 

Thanks & Regards, 

Anurag Agnihotri

**Comment by iSevenDays** [comment]
Hi Anurag15990,

Could you please attach your test project and give us steps to reproduce the issue?

Thanks!

**Comment by Anurag15990** [comment]
Hey iSevenDays,

Do you need an ipa or build of the test project?

**Comment by iSevenDays** [comment]
I need to debug your test project(source code required) and also I need steps to reproduce the issue

If you provide us with this information, it will be much faster for us to find and fix the bug

Thanks!

**Comment by Raikerian** [comment]
Hi,

were you able to fix this issue?

**Comment by Raikerian** [comment]
Please run this code snippet in order to check if cache is empty:

``` swift
QMServicesManager.instance().cachedDialogs { (dialogs : [AnyObject]!) -> Void in
            print(dialogs.count)
        }
```

Please note that memory storage is not a cache. Memory storage is getting filled on QMChatService run time, not the same time app starts, but with quiet a bit of delay. Cause cache loading is asynchronous method.

If you are still having any troubles please let us know by creating a separate issue :)
