### ISSUE TITLE
You don't have appropriate permissions to perform this operation

### ISSUE THREAD

**Issue by estysherman** [QuickBlox/q-municate-services-ios#187]
in adding member to group in quickblox android i get: You don't have appropriate permissions to perform this operation.

 private boolean UpdateDialogGroupQBUsers(int userId) {

```
        QBRequestUpdateBuilder requestBuilder = new QBRequestUpdateBuilder();
        requestBuilder.push("occupants_ids", userId); // add another users
        QBChatService.getInstance().getGroupChatManager().updateDialog(QBDialog, requestBuilder,           new QBEntityCallback<QBDialog>() {
            @Override
            public void onSuccess(QBDialog dialog, Bundle args) {
                Log.d("addMember", "success");
                isSuccess = true;
            }

            @Override
            public void onError(QBResponseException e) {
                Log.d("addMember",e.toString());
                isSuccess = false;
            }
        });
        return isSuccess;
    }
}
```

**Comment by ghost** [comment]
Hi @estysherman,
For android issues we have another repo. [Android SDK](https://github.com/QuickBlox/quickblox-android-sdk/)
Please, look at this issue. It's similar with yours. [Permission issue](https://github.com/QuickBlox/quickblox-android-sdk/issues/20)

**Comment by estysherman** [comment]
Hi,
Thanks for responding to me,
I wrote the question in android sdk too.
About the issue. that similar with mine
I saw him but he does not help me,
Still I get the same error.
do you have another idea what the cause of my error?

**Comment by Raikerian** [comment]
@estysherman This could be android SDK issue. But I can try to help you. In your code you are trying to add member to the group dialog. Am I correct?
If yes, make sure that you are existent in occupants IDs of that group dialog, cause you need to be there in order to perform such operation.

Also make sure, that dialog type is Group dialog. Not private dialog nor a public group. It just has to be a group dialog (type 2). You cannot add people to private dialog and there is no need to add people to the public group (it is working without occupants).

You can read a detailed doc about dialog types here: http://quickblox.com/developers/Chat#Create_dialog

**Comment by estysherman** [comment]
I checked what you wrote,
I'm existent in occupants IDs
And the type of dialog is Group.
But it did not help me
I still get the same error.
