### ISSUE TITLE
A crash bug.

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#222]
_Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/q-municate-services-ios/issues)_

**Environment details**
_iOS version, Quickblox iOS SDK version, QMServices version_
iOS 9.3.2
QuickBlox 3.7.2
QMServices version 0.4

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
_Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))_
![screen shot 2016-06-04 at 6 34 48 pm](https://cloud.githubusercontent.com/assets/1511264/15799332/3fe75e4e-2a83-11e6-849a-83252b40c5ae.png)

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

Thank you for reporting the issue, but I'm not sure if it is actually on our side. The method you got crash from is this: https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMChatCache/QMChatCache/QMChatCache.m#L115

As you can see the array in there is not mutable. You have probably got that crash because you send a mutable instance of array in this method.

**Comment by tranngoclinh88** [comment]
Thank @Raikerian. I'll check on my side.
